---
title: "`r paste('Report for', params$type)`"
output: pdf_document
params:
  type: ''
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
dt <- read_csv('https://raw.githubusercontent.com/fivethirtyeight/data/master/alcohol-consumption/drinks.csv')
dt <- dt %>% 
          gather('type', 'servings', beer_servings:wine_servings) %>% 
          filter(type == params$type)
right_join(dt, map_data("world"), by = c('country' = 'region')) %>% 
  ggplot() + 
  geom_polygon(aes(x = long, y = lat, group = group, fill = servings), color = "white") + 
  coord_fixed(1.3) +
  ggtitle(paste('Consumption of', params$type))

```

The country with the highest consumption is `r filter(dt, servings == max(servings)) %>% pull(country)` with `r filter(dt, servings == max(servings)) %>% pull(servings)` per person.

There are a few contry names that are not matching - but our focus was on parametrizing the repo. For a complete graph you should take care of the followings:

```{r}
anti_join(dt, map_data("world"), by = c('country' = 'region')) 
```


